name: Build CLI

on:
  push:
    branches: [ master ]
#   pull_request:
#     branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        # rid: ['win-x64', 'linux-x64']
        dotnet: [ '5.0.x' ]
        
    name: build

    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - run: dotnet restore Shokofin/Shokofin.csproj
      - run: dotnet publish -c Release Shokofin/Shokofin.csproj
      - uses: actions/upload-artifact@v2
        with:
          name: Shokofin
          path: Shokofin/bin/Release/net5.0/Shokofin.dll
