name: Build CLI

on:
  push:
    branches: [ master ]
#   pull_request:
#     branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        # rid: ['win-x64', 'linux-x64']
        dotnet: [ '3.1.x' ]
        
    name: build

    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - run: dotnet restore Shokofin/Shokofin.csproj -s https://api.nuget.org/v3/index.json -s https://pkgs.dev.azure.com/jellyfin-project/jellyfin/_packaging/unstable/nuget/v3/index.json
      - run: dotnet publish -c Release Shokofin/Shokofin.csproj
      - uses: actions/upload-artifact@v2
        with:
          name: Shokofin
          path: Shokofin/bin/Release/netstandard2.1/Shokofin.dll
